import { Roboto } from 'next/font/google';
import './globals.css';
import Header from './_component/header';
import Footer from './_component/footer';
import { ClerkProvider } from '@clerk/nextjs';

// Import Turret Road font
const turretRoad = Roboto({
	subsets: ['latin'], // You can add other subsets if needed
	weight: ['400', '700'], // Specify the weights you need
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={turretRoad.className}>
					<Header />
					<div>{children}</div>
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
